### ISSUE TITLE
net::ERR_CONNECTION_REFUSED at http://localhost:8889/wp-admin/

### ISSUE THREAD

**Issue by martynbiz** [liip/e2e-tests-example-wp-plugin#5]
I've simply cloned this repo, run `npm install` then `npm run test:e2e`. However, I'm seeing many of the following errors:

```
> npm run test:e2e

> e2e-tests-example@1.0.0 test:e2e C:\Users\marty\Sites\nmis-wp\wp-content\plugins\e2e-tests-example-wp-plugin
> wp-scripts test-e2e

 FAIL  e2e-tests/wrapper-block.spec.js (14.704s)
  ● Wrapper block › Wrapper block should be available

    net::ERR_CONNECTION_REFUSED at http://localhost:8889/wp-admin/post-new.php

      at navigate (node_modules/puppeteer/lib/FrameManager.js:120:37)
        -- ASYNC --
      at Frame.<anonymous> (node_modules/puppeteer/lib/helper.js:111:15)
      at Page.goto (node_modules/puppeteer/lib/Page.js:675:49)
      at Page.goto (node_modules/puppeteer/lib/helper.js:112:23)
      at _callee$ (node_modules/@wordpress/e2e-test-utils/build/@wordpress/e2e-test-utils/src/visit-admin-page.js:20:13)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:271:22)
      ...
```

I can't see where post 8889 has been declared. I followed the readme instructions to the word. I'm guessing this is a server that is initiated during the running of the tests? Any help? Thanks

I'm running:
Windows 10

> npm -v
6.14.4
> node -v
v10.20.1

**Comment by joneslloyd** [comment]
Same for me

**Comment by akaufman3** [comment]
Same for me - I just found this possible solution and was going to try and give a go: https://stackoverflow.com/questions/63846293/wordpress-gutenberg-e2e-testing-neterr-connection-refused-at-http-localhos
